language: c

compiler:
- gcc
- clang

python:
- "3.6"

before_script:
- mkdir build
- cd build
- cmake ..
- cmake --version
- python3 --version

script: 
- make
- make test

addons:
  apt:
    packages:
      - cmake