language: c

compiler:
- gcc
- clang

dist: xenial

python:
- "3.6"

before_script:
- mkdir build
- cd build
- cmake ..
- cmake --version
- python3 --version

script: 
- make
- make check

addons:
  apt:
    packages:
      - cmake