dist: xenial
# language: python
# python: 3.7

# compiler:
# - gcc
# - clang

# python: 3.6



matrix:
  include:
    - language: python
      python: 3.6

    - language: c
      compiler:
      - gcc
      - clang

before_script:
- mkdir build
- cd build
- cmake ..
- cmake --version
- python3 --version

script: 
- make
- make check

addons:
  apt:
    packages:
      - cmake