." Comments are written by typing ." at the beginning of a line.

." HEADER / FOOTER
.TH 42sh 1 "May 22, 2019" "version 1.0"

." SECTION NAME
.SH NAME
42sh \- open a shell based on an UNIX shell



." SECTION SYNOPSYS
.SH SYNOPSIS
.B ./42sh [options] [commands]



." SECTION DESCRIPTION
.SH DESCRIPTION
.B 42sh
is a shell that can interpret commands. Based on an UNIX shell, it can also
parse a entiere \fBSCL\fR and execute it.



." SECTION OPTION
.SH OPTIONS

.TP
.BR \-\-version
Display the version of the 42sh.




." BUGS SECTION
.SH BUGS
.TP
not any known bug actually



." AUTHORS SECTION
.SH AUTHOR
A group of 5 EPITA students participated to the conception of this \fB42sh\fR.
Tristan Dietz <tristan.dietz@epita.fr>, 
Jiemiao Zheng <jiemiao.zheng@epita.fr>,
Safa Kilic <safa.kilic@epita.fr>,
Fatou Camara <fatou.camara@epita.fr>,
Souleymane Ba <souleymane.ba@epita.fr>.
